server.port=8080
spring.application.name=api-gateway

spring.main.web-application-type=reactive

# ==========================================
# 1. USER SERVICE ROUTE (Port 8081)
# ==========================================
spring.cloud.gateway.routes[0].id=user-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].uri=http://user-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/alphapay/user/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter

# ==========================================
# 2. WALLET SERVICE ROUTE (Port 8083)
# ==========================================
spring.cloud.gateway.routes[1].id=wallet-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].uri=http://wallet-service:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/alphapay/wallet/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

# ==========================================
# 3. TRANSACTION SERVICE ROUTE (Port 8082)
# ==========================================
spring.cloud.gateway.routes[2].id=transaction-service
#spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].uri=http://transaction-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/alphapay/transactions/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter