server.port=8080
spring.application.name=api-gateway

spring.main.web-application-type=reactive

# Route ki ID
spring.cloud.gateway.routes[0].id=user-service

# User service kahan chal rahi hai
spring.cloud.gateway.routes[0].uri=http://localhost:8081

# Agar URL mein /api/users/ hai, toh is route par bhejo
spring.cloud.gateway.routes[0].predicates[0]=Path=/alphapay/user/**

# Humara custom JWT Security filter is route par apply karein
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter