plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.magictech.alphapay'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.magictech.alphapay"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    // Retrofit for Network Calls
    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    // GSON Converter for handling JSON responses
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    // Handles raw scalar types (Strings, primitives) from backend responses
    implementation "com.squareup.retrofit2:converter-scalars:2.9.0"
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}