server.port=8081
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
#spring.application.name=Alpha Pay
spring.application.name=user-service

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.walletServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.walletServiceCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.walletServiceCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.walletServiceCB.wait-duration-in-open-state=30000ms
resilience4j.circuitbreaker.instances.walletServiceCB.permitted-number-of-calls-in-half-open-state=3

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true